// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('g:/updropp/node_modules/react');
var { Component } = React;
var ReactNative = require('g:/updropp/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('retireditems', appParameters);
});
require('g:/updropp/index.js');